### ISSUE TITLE
TypeError: Softonic\GraphQL\DataObjectBuilder::build(): Argument #1 ($data) must be of type array, null given

### ISSUE THREAD

**Issue by 4n70w4** [softonic/graphql-client#65]
```
softonic/graphql-client                    2.2.0              Softonic GraphQL client
```

```
TypeError: Softonic\GraphQL\DataObjectBuilder::build(): Argument #1 ($data) must be of type array, null given, called in /var/www/html/vendor/softonic/graphql-client/src/DataObjectBuilder.php on line 45 and defined in /var/www/html/vendor/softonic/graphql-client/src/DataObjectBuilder.php:36
```

Stack trace:
```
#0 /var/www/html/vendor/softonic/graphql-client/src/DataObjectBuilder.php(45): Softonic\GraphQL\DataObjectBuilder->build(NULL, Array)
#1 /var/www/html/vendor/softonic/graphql-client/src/DataObjectBuilder.php(54): Softonic\GraphQL\DataObjectBuilder->build(Array, Array)
#2 /var/www/html/vendor/softonic/graphql-client/src/DataObjectBuilder.php(45): Softonic\GraphQL\DataObjectBuilder->build(Array, Array)
#3 /var/www/html/vendor/softonic/graphql-client/src/DataObjectBuilder.php(54): Softonic\GraphQL\DataObjectBuilder->build(Array, Array)
#4 /var/www/html/vendor/softonic/graphql-client/src/DataObjectBuilder.php(28): Softonic\GraphQL\DataObjectBuilder->build(Array, Array)
#5 /var/www/html/vendor/softonic/graphql-client/src/ResponseBuilder.php(49): Softonic\GraphQL\DataObjectBuilder->buildQuery(Array)
#6 /var/www/html/vendor/softonic/graphql-client/src/ResponseBuilder.php(20): Softonic\GraphQL\ResponseBuilder->getNormalizedResponse('{"data":{"query...')
#7 /var/www/html/vendor/softonic/graphql-client/src/Client.php(65): Softonic\GraphQL\ResponseBuilder->build(Object(GuzzleHttp\Psr7\Response))
#8 /var/www/html/vendor/softonic/graphql-client/src/Client.php(33): Softonic\GraphQL\Client->executeQuery('query Edits($in...', Array)
```

Part of response to reproduce:

```json
"images":[{"uuid":"1234567890","url":"url"},null],
```

Hotfix:
![image](https://github.com/softonic/graphql-client/assets/38257723/6156af96-5ece-44b7-a99d-c3a02c9c7ba0)

**Comment by joskfg** [comment]
Hello,

Thanks for creating the issue. Could you post a simple schema and the query that reproduce the problem?

**Comment by joskfg** [comment]
Can't reproduce

**Comment by cweiske** [comment]
I see the same problem with a Drupal 9 GraphQL response. An array of `relatedNodes.entities` contains two values: One object, and one `null` value. The `null` value is because permission checks in Drupal make this specific object unavailable to the user.

![2024-06-13 graphql dump null-2](https://github.com/softonic/graphql-client/assets/59036/a0e1fdd2-8e64-471d-97a8-f434129b8fab)

The schema view for `relatedNodes` in the GraphQL explorer shows
> type: EntityQueryResult!
> fields:
> - count: Int
> - entities(language: LanguageId = null): [Entity]

so null values are probably not allowed for `entities`.

`EntityQueryResult` schema extracted from the huge full schema:
```
{
  "kind": "OBJECT",
  "name": "EntityQueryResult",
  "description": "Wrapper type for entity query results containing the list of loaded entities and the full entity count for pagination purposes.",
  "fields": [
    {
      "name": "count",
      "description": null,
      "args": [],
      "type": {
        "kind": "SCALAR",
        "name": "Int",
        "ofType": null
      },
      "isDeprecated": false,
      "deprecationReason": null
    },
    {
      "name": "entities",
      "description": null,
      "args": [
        {
          "name": "language",
          "description": "",
          "type": {
            "kind": "ENUM",
            "name": "LanguageId",
            "ofType": null
          },
          "defaultValue": "null"
        }
      ],
      "type": {
        "kind": "LIST",
        "name": null,
        "ofType": {
          "kind": "INTERFACE",
          "name": "Entity",
          "ofType": null
        }
      },
      "isDeprecated": false,
      "deprecationReason": null
    }
  ],
  "inputFields": null,
  "interfaces": [],
  "enumValues": null,
  "possibleTypes": null
},
```

**Comment by cweiske** [comment]
@joskfg could you please reopen this?

Related: https://www.drupal.org/project/graphql_core_schema/issues/3589490
